// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA07YHg3X50oJL2S7yV5BOkSecTrxw7lw',
    appId: '1:524203350619:android:f2f5348b1d503dd88e3d7e',
    messagingSenderId: '524203350619',
    projectId: 'chat-with-gemini-91d07',
    storageBucket: 'chat-with-gemini-91d07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyAy62jRJ2xr7FHcv1mMDUT9DSfZe-UiM',
    appId: '1:524203350619:ios:1ce8103648c6013b8e3d7e',
    messagingSenderId: '524203350619',
    projectId: 'chat-with-gemini-91d07',
    storageBucket: 'chat-with-gemini-91d07.firebasestorage.app',
    iosClientId: '524203350619-u4kriajlal701jls3vk8kb6sdep8mefq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatWithGemini',
  );
}
